# Default values for myapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# values.yaml

env:
  - name: ASPNETCORE_URLS
    value: "http://*:80"
  - name: ASPNETCORE_ENVIRONMENT
    value: "Development"

replicaCount: 1

image:
  repository: dean377/project2
  pullPolicy: IfNotPresent
  tag: v3

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

healthCheckPath: /swagger/index.html
